config/routes.rb
Rails.application.routes.draw do

  scope '/(:locale)', locale: /#{I18n.available_locales.join('|')}/ do
    # Static pages and routes
    match '/contacts', to: 'static_pages#contacts', as: :contacts, via: :get
    match '/riga', to: 'static_pages#riga', as: :riga, via: :get
    root 'static_pages#index'
  end

  get '/:locale' => 'static_pages#index'
  root to: redirect("/#{I18n.default_locale}", status: 302),
       as: :redirected_root

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :set_locale

  def set_locale
      I18n.locale = params[:locale] || I18n.default_locale
  end

  def self.default_url_options(options={})
    { locale: I18n.locale }
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end

  def riga
  end

  def contacts
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Nord Alliance</title>
	<link href='http://fonts.googleapis.com/css?family=Roboto+Condensed:700italic,400,300,700' rel='stylesheet' type='text/css'>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
		<!-- Header -->
		<div id="header">
			<div class="container">
					
				<!-- Logo -->
					<div id="logo">
						<h1><a href="<%= root_path %>">Nord Alliance</a></h1>
					</div>
				
				<!-- Nav -->
					<nav id="nav">
						<ul>
							<li><a href="<%= root_path %>"><%= t('main') %></a></li>
							<li><a href="http://www.ooo-transcontinent.ru"><%= t('partner') %></a></li>
							<!-- <li><a href="<%= riga_path %>">Office in Latvia</a></li> -->
							<li><a href="<%= contacts_path %>"><%= t('contacts') %></a></li>
						</ul>
					</nav>

			</div>
		</div>
	<!-- Header -->
		
	<%= yield %>

	<!-- Copyright -->
	<div id="copyright" class="container">
		Design: <a href="http://templated.co">TEMPLATED</a> Images: <a href="http://unsplash.com">Unsplash</a> (<a href="http://unsplash.com/cc0">CC0</a>)
	</div>
</body>
</html>

app/views/static_pages/contacts.html.erb
<!-- Main -->
<div id="page">


	<div class="container">
		<h1>Scotland, Inverness</h1>
		<p>e-mail: inverness@nordalliance.co.uk</p>
		<p>phone: +441463288700</p>
		<p>address: 45 Rosehaugh road, Inverness, Scotland</p>
		<div class="cc-map-wrapper">
			<iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d2144.3319825095873!2d-4.240639099999999!3d57.4897123!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x488f76a9d90f5569%3A0xbd530009b492757!2zNDUgUm9zZWhhdWdoIFJkLCBJbnZlcm5lc3MsIEhpZ2hsYW5kIElWMyA4U1csINCS0LXQu9C40LrQvtCx0YDQuNGC0LDQvdC40Y8!5e0!3m2!1sru!2sru!4v1425257830715" width="600" height="450" frameborder="0" style="border:0"></iframe>
		</div>
	</div>

	<br>

	<div class="container">
		<h1>Latvia, Riga</h1>
		<p>e-mail: riga@nordalliance.co.uk</p>
		<p>phone: +37167660664</p>
		<p>address: Regus Riga Bussiness Center, 14 Terbatas street, Riga, Latvia</p>
		<div class="cc-map-wrapper">
			<iframe src="https://www.google.com/maps/embed?pb=!1m16!1m12!1m3!1d2175.714218154345!2d24.121577599999988!3d56.953697399999974!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!2m1!1s14+Terbatas+street%2C+Riga!5e0!3m2!1sru!2sru!4v1425258105170" width="600" height="450" frameborder="0" style="border:0"></iframe>
		</div>

	</div>

	<br>

	<div class="container">
		<h1>Russia, Moscow (Main partner)</h1>
		<p>e-mail: info@ooo-transcontinent.ru</p>
		<p>phone: +74959759662
		<p>address: 6/4, Chasovaya street, Moscow, Russia</p>

		<div class="cc-map-wrapper">
			<iframe src="https://www.google.com/maps/embed?pb=!1m16!1m12!1m3!1d2242.1893542926705!2d37.534804000000015!3d55.80731299999998!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!2m1!1sChasovaya%2C+6%2F4%2C+Moscow!5e0!3m2!1sru!2sru!4v1425258277447" width="600" height="450" frameborder="0" style="border:0"></iframe>
		</div>


	</div>
</div

app/views/static_pages/contacts.ru.html.erb
<!-- Main -->
<div id="page">


	<div class="container">
		<h1>Шотландия, Инвернесс</h1>
		<p>e-mail: inverness@nordalliance.co.uk</p>
		<p>Телефон: +441463288700</p>
		<p>Адрес: 45 Rosehaugh road, Inverness, Scotland</p>
		<div class="cc-map-wrapper">
			<iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d2144.3319825095873!2d-4.240639099999999!3d57.4897123!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x488f76a9d90f5569%3A0xbd530009b492757!2zNDUgUm9zZWhhdWdoIFJkLCBJbnZlcm5lc3MsIEhpZ2hsYW5kIElWMyA4U1csINCS0LXQu9C40LrQvtCx0YDQuNGC0LDQvdC40Y8!5e0!3m2!1sru!2sru!4v1425257830715" width="600" height="450" frameborder="0" style="border:0"></iframe>
		</div>
	</div>

	<br>

	<div class="container">
		<h1>Латвия, Рига</h1>
		<p>e-mail: riga@nordalliance.co.uk</p>
		<p>Телефон: +37167660664</p>
		<p>Адрес: Regus Riga Bussiness Center, 14 Terbatas street, Riga, Latvia</p>
		<div class="cc-map-wrapper">
			<iframe src="https://www.google.com/maps/embed?pb=!1m16!1m12!1m3!1d2175.714218154345!2d24.121577599999988!3d56.953697399999974!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!2m1!1s14+Terbatas+street%2C+Riga!5e0!3m2!1sru!2sru!4v1425258105170" width="600" height="450" frameborder="0" style="border:0"></iframe>
		</div>

	</div>

	<br>

	<div class="container">
		<h1>Россия, Москва (Основной партнер)</h1>
		<p>e-mail: info@ooo-transcontinent.ru</p>
		<p>Телефон: +74959759662
		<p>Адрес: 6/4, Chasovaya street, Moscow, Russia</p>

		<div class="cc-map-wrapper">
			<iframe src="https://www.google.com/maps/embed?pb=!1m16!1m12!1m3!1d2242.1893542926705!2d37.534804000000015!3d55.80731299999998!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!2m1!1sChasovaya%2C+6%2F4%2C+Moscow!5e0!3m2!1sru!2sru!4v1425258277447" width="600" height="450" frameborder="0" style="border:0"></iframe>
		</div>


	</div>
</div

app/views/static_pages/index.html.erb
<!-- Banner -->
<div id="banner">
	<div class="container">
	</div>
</div>
<!-- /Banner -->

<!-- Main -->
<div id="page">

	<!-- Extra -->
	<div id="marketing" class="container">
		<div class="row">
			<div class="4u">
				<section>
					<header>
						<h2>Shipping by truck</h2>
					</header>
					<p><img src="<%= asset_path('truck.jpg') %>" alt=""></p>
					<p class="subtitle">For movement of up country cargo to and for port transportation by road is preferred because this mode is readily available thus cutting down waiting time. Rail transportation though cheaper but due to shortage of rail wagons a lot of waiting time is required. 
We have a fleet of heavy duty trucks and trailers for transporting containers and open bulk cargo.</p>
				</section>
			</div>
			<div class="4u">
				<section>
					<header>
						<h2>Shipping by air</h2>
					</header>
					<p><img src="<%= asset_path('plane.jpg') %>" alt=""></p>
					<p class="subtitle">Airfreight is the fastest and most reliable transport mode. It creates shorter lead-times in time-based and just-in-time systems. It reduces your costs through reduced stock and faster distribution. And finally, its speed and flexibility increases your service level. 
With this team of specialist airfreight experts and its state of the art technology, Nort Alliance, offers faster, more extensive services for point-to-point delivery of goods to domestic, regional and international destinations than most Europe companies. Over the years, Nord Alliance, has forged close and successful partnerships with international cargo shippers, agents and allied airline representatives, providing quality service in handling nearly every type of cargo.</p>
				</section>
			</div>
			<div class="4u">
				<section>
					<header>
						<h2>Shipping by sea</h2>
					</header>
					<p><img src="<%= asset_path('ship.jpg') %>" alt=""></p>
					<p class="subtitle">Container vessels is capable of handling container shipment from / to major Europe port.
In order to meet the growing traffic of container trade and facilitate effective and speedy handling of containers, cargo international has acquired and developed a modern container terminal in Europe ports . 
We working with biggest lines in the world</p>
				</section>
			</div>
		</div>
	</div>
	<!-- /Extra -->
	<br><hr><br>
  <div class="container">
		<div class="row">
	    <header>
		  	<h2>Our Mission</h2>
			</header>
			<p>We are deeply proud of the contribution we can make in our daily work. Everything that is moved from one place to another needs the aid of logistics – but behind this simple truth one finds millions of stories. As the logistics company for the world, we form the backbone of trade, ensuring that whatever needs to be delivered, gets delivered. A shipment placed in our trust may include life-saving medicines, or a birthday present from a friend, or hold a company’s entire existence in the form of a prototype. We not only deliver parcels and packages, and make sure containers arrive at ports: we deliver prosperity, we transport health, we power growth, we deliver joy. Every day we connect people, improving their lives. </p>
		</div>
	</div>

				<br>

	<div class="container">
		<div class="row">
	 
						<p><a href="/ru">Русская версия сайта</a></p>
    </div>
  </div>
</div>
<!-- /Main -->

app/views/static_pages/index.ru.html.erb
<!-- Banner -->
<div id="banner">
	<div class="container">
	</div>
</div>
<!-- /Banner -->

<!-- Main -->
<div id="page">

	<!-- Extra -->
	<div id="marketing" class="container">
		<div class="row">
			<div class="4u">
				<section>
					<header>
						<h2>Автомобильные перевозки</h2>
					</header>
					<p><img src="<%= asset_path('truck.jpg') %>" alt=""></p>
					<p class="subtitle">Для перемещения грузов в порты и из портов предпочтительным является автомобильная транспортировка, так как она позволяет значительно сократить время транспортировки. Не смотря на то что железнодорожные перевозки выгоднее с финансовой точки зрения, но с точки зрения сроков доставки - автомобильной транспортировке на не большие расстояния нет равных.</p>
				</section>
			</div>
			<div class="4u">
				<section>
					<header>
						<h2>Авиаперевозки</h2>
					</header>
					<p><img src="<%= asset_path('plane.jpg') %>" alt=""></p>
					<p class="subtitle">Авиаперевозки являются самым быстрым и надежным видом. Это позволяет доставлять грузы за минимальное время и точно в срок. Также это позволяет снизить затраты за счет снижения объема складских запасов, ведь новую партию вы получите быстро и точно в срок. И, наконец, скорость и гибкость авиаперевозок позволяют поднять уровень сервиса на качественно новый уровень.
					С нашей командой специалистов в данной области Вы с легкостью осуществите транспортировку грузов в национальных, региональных и международных направлениях. На протяжении нескольких лет Nord Alliance укрепляет успешные партнерские отношения с международными перевозчиками, агентами и авиакомпаниями обеспечивая наивысшее качество обслуживания.</p>
				</section>
			</div>
			<div class="4u">
				<section>
					<header>
						<h2>Морские транспортировки</h2>
					</header>
					<p><img src="<%= asset_path('ship.jpg') %>" alt=""></p>
					<p class="subtitle">Морские контейнерные перевозки позволяют транспортировать значительные объемы грузов. Для того чтобы удовлетворить растущий трафик контейнерных перевозок которые приобретает соверменный мир наши представители и агенты находятся практически в каждом крупном порту Европы.
				Мы работаем с крупнейшими судоходными компаниями в мире.</p>
				</section>
			</div>
		</div>
	</div>
	<!-- /Extra -->
	<br><hr><br>
  <div class="container">
		<div class="row">
	    <header>
		  	<h2>Наша миссия</h2>
			</header>
			<p>Мы гордимся вкладом, который вносим благодаря нашей повседневной работе. Все, что перевозится с одного места на другое, требует помощи логистики – но за этой простой правдой прячутся миллионы историй. Как логистическая компания, действующая по всему миру и обеспечивающая транспортировку всего того, что должно быть доставлено, мы формируем основу для международной торговли. Груз, который доверил нам клиент, может представлять из себя жизненно важные медикаменты, подарок ко Дню рождения друга, а может содержать в себе будущее компании, например, прототип инновационного устройства, будущего лидера продаж. Мы не только перевозим грузы и документы и обеспечиваем прибытие контейнеров в порты – мы доставляем процветание, мы транспортируем здоровье, мы обеспечиваем рост, мы доставляем радость. Каждый день мы соединяем людей, улучшая их жизнь.
			</p>
		</div>
	</div>

	<br>
	<div class="container">
		<div class="row">
	 
						<p><a href="/ru">English version</a></p>
    </div>
  </div>

</div>
<!-- /Main -->